#!/bin/bash
# Create a MySQL user with limited privileges for backup purposes.
# ==============================================================================
# Enter into a BASH shell:
mysql -u root -p << EOF
CREATE USER 'backup_user'@'localhost' IDENTIFIED BY 'nicelongpassword';
GRANT SELECT, SHOW VIEW, RELOAD, REPLICATION CLIENT, EVENT, TRIGGER ON *.* TO 'backup_user'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'backup_user'@'localhost';
EOF
