#!/bin/bash
#
# Set up the incremental backup. Run as sudo.
# ------------------------------------------------------------------------------
# Set directory
THIS=$(readlink -f "${BASH_SOURCE[0]}")
PROJECT_DIR=$(dirname "${THIS}")
CONFIG_FILE="${PROJECT_DIR}/server-backup.conf"
SERVERNAME=$(hostname -s)

# Include project specific dependencies
[[ ! -f "${CONFIG_FILE}" ]] && { echo "Config file missing at ${CONFIG_FILE}"; exit 1; }
# shellcheck disable=SC1090
. "${CONFIG_FILE}"

BACKUP_USERNAME="${SERVERNAME}backup"
PARENT_DIR="/home/${BACKUP_USERNAME}"
BACKUP_PATH="${PARENT_DIR}/backup"
SRC="${PARENT_DIR}/source"
DB_DUMPS_PATH="${SRC}/sql"
CONFIG="${SRC}/config"

function create_backup_user {
	[[ $(getent passwd "${BACKUP_USERNAME}") ]] && { echo "${BACKUP_USERNAME} exists."; return 0; }

	local match=0
	local new_pass=
	local conf=
	while [ "${match}" -eq "0" ]; do
		read -srp "Enter new UNIX password: " new_pass
		printf "\n"
		read -srp "Retype new UNIX password: " conf
		printf "\n"
		if [[ "${new_pass}" != "${conf}" ]]; then
			echo "Passwords do not match. Try again."
		else
			match=1
		fi
	done
	adduser --disabled-password "${BACKUP_USERNAME}"
	echo "${BACKUP_USERNAME}:${new_pass}" | chpasswd
	usermod -aG sudo "${BACKUP_USERNAME}"
}

function create_mysql_backup_user {
	sudo mysql -u root -e "
	CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASSWD}';
	GRANT SELECT, SHOW VIEW, RELOAD, REPLICATION CLIENT, EVENT, TRIGGER ON *.* TO '${MYSQL_USER}'@'localhost';
	FLUSH PRIVILEGES;
	SHOW GRANTS FOR '${MYSQL_USER}'@'localhost';
	"
}

function setup_dirs {
	# Make the Backup directory
	mkdir -p "${BACKUP_PATH}"

	# Make the source directory
	mkdir -p "${SRC}"

	# Make the config directory if it does not exist.
	mkdir -p "${CONFIG}"

	# Make the target for mysqldump
	mkdir -p "${DB_DUMPS_PATH}"

	# Add a symlink to site files into the source directory.
	ln -s /var/www/html "${SRC}"

	# Symlink Apache config files into source/config (including vhosts setup)
	ln -s /etc/apache2 "${CONFIG}"

	# Symlink MySQL config files
	ln -s /etc/mysql "${CONFIG}"

	# Make the backup script executable
	chmod +x "${PROJECT_DIR}"/server-backup

	# Symlink MySQL config files
	ln -s "${PROJECT_DIR}"/server-backup /usr/local/sbin
}

echo "
This script sets up backup directories and necessary symlinks.
You only need to run this script ONCE. It's probably a good idea to read the readme!
Before running, server specific variables must be set in ${PROJECT_DIR}/variables.
If you haven't done this, stop and do so before continuing.
"

read -rp "Do you want to proceed? [y/N]?" choice
[[ ! "${choice}" =~ ^(yes|YES|y|Y)$ ]] && { echo "Exiting."; exit 1; }

create_backup_user
#create_mysql_backup_user
setup_dirs
